spring:
  application:
    name: api-client

server:
  port: 2020

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
